spring.application.name=eventostec-api

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://eventostec-database.cylmys6g6gta.us-east-1.rds.amazonaws.com/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

aws.region=${AWS_REGION:us-east-1}
aws.bucket.name=${AWS_BUCKET_NAME:eventostec-photoss}
