spring.application.name=eventostec-api
spring.datasource.url=jdbc:postgresql://eventostec-database.cylmys6g6gta.us-east-1.rds.amazonaws.com/postgres
spring.datasource.username=postgres
spring.datasource.password=.L.vEmZ$h]j*V>epEFLZR6(1wIH:
aws.region=us-east-1
aws.bucket.name=eventostec-photoss