spring.application.name=eventostec-api

spring.profiles.default=dev

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

aws.region=${AWS_REGION:us-east-1}
aws.bucket.name=${AWS_BUCKET_NAME:eventostec-photoss}
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}
